# Generated by Django 4.2.3 on 2023-07-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_cart_total_price_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
