# Generated by Django 4.2.3 on 2023-08-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_banner_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='artist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
