# Generated by Django 4.2.3 on 2023-08-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_image_product_image_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('RAZORPAY', 'razorpay'), ('CASH_ON_DELIVERY', 'Cash on Delivery'), ('Wallet pay', 'Wallet pay')], default='Cash on Delivery', max_length=20),
        ),
    ]
